# Generated by Django 4.2.5 on 2023-10-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
        migrations.DeleteModel(
            name='DetalleListadoDePedidos',
        ),
        migrations.DeleteModel(
            name='DetalleVentas',
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='ListadoPedidos',
        ),
        migrations.DeleteModel(
            name='Marcas',
        ),
        migrations.DeleteModel(
            name='MetodosPago',
        ),
        migrations.DeleteModel(
            name='MovimientoCaja',
        ),
        migrations.DeleteModel(
            name='Movimientos',
        ),
        migrations.DeleteModel(
            name='Presentacion',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='Proveedores',
        ),
        migrations.DeleteModel(
            name='Puestos',
        ),
        migrations.DeleteModel(
            name='UnidadesMedidas',
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
