# Generated by Django 4.2.7 on 2023-11-13 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(db_column='ID_caja', primary_key=True, serialize=False)),
                ('anio', models.CharField(db_column='Anio', max_length=4)),
                ('mes', models.CharField(db_column='Mes', max_length=10)),
                ('total_gastos', models.DecimalField(db_column='Total_gastos', decimal_places=4, max_digits=19)),
                ('total_ingresos', models.DecimalField(db_column='Total_ingresos', decimal_places=4, max_digits=19)),
                ('total_caja', models.DecimalField(db_column='Total_caja', decimal_places=4, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(db_column='ID_categoria', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(db_column='Nombre_categoria', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=100, null=True)),
                ('estado', models.BooleanField(db_column='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.BigAutoField(db_column='ID_compra', primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField(blank=True, db_column='Fecha_compra', null=True)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=100, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(db_column='ID_empleado', primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(db_column='Primer_nombre', max_length=50)),
                ('segundo_nombre', models.CharField(db_column='Segundo_nombre', max_length=50)),
                ('otros_nombres', models.TextField(blank=True, db_column='Otros_nombres', null=True)),
                ('primer_apellido', models.CharField(db_column='Primer_apellido', max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, db_column='Segundo_apellido', max_length=50, null=True)),
                ('apellido_casada', models.CharField(blank=True, db_column='Apellido_casada', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marcas', models.AutoField(db_column='ID_marcas', primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(db_column='Nombre_marca', max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=150, null=True)),
                ('estado', models.BooleanField(db_column='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id_metodo_pago', models.AutoField(db_column='ID_metodo_pago', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id_movimiento', models.AutoField(db_column='ID_movimiento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id_presentacion', models.AutoField(db_column='ID_presentacion', primary_key=True, serialize=False)),
                ('nombre_presentacion', models.CharField(db_column='Nombre_presentacion', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(db_column='ID_proveedor', primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(blank=True, db_column='Nombre_proveedor', max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('estado', models.BooleanField(db_column='Estado', null=True)),
                ('dia_visita', models.CharField(blank=True, db_column='Dia_visita', max_length=25, null=True)),
                ('dia_entrega', models.CharField(blank=True, db_column='Dia_entrega', max_length=25, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id_puestos', models.AutoField(db_column='ID_puestos', primary_key=True, serialize=False)),
                ('nombre_puesto', models.CharField(db_column='Nombre_puesto', max_length=25)),
                ('detalles', models.CharField(blank=True, db_column='Detalles', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesMedidas',
            fields=[
                ('id_medicion', models.AutoField(db_column='ID_medicion', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=20)),
                ('prefijo', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.BigAutoField(db_column='ID_venta', primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(blank=True, db_column='fecha_Venta', null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fk_empleado1', models.ForeignKey(blank=True, db_column='fk_empleado1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion_app.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_productos', models.AutoField(db_column='ID_productos', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(db_column='Nombre_producto', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=100, null=True)),
                ('codigo_barras', models.CharField(blank=True, db_column='Codigo_barras', max_length=20, null=True)),
                ('tamanio', models.DecimalField(db_column='Tamanio', decimal_places=2, max_digits=4)),
                ('imagen', models.BinaryField(db_column='Imagen')),
                ('estado', models.BooleanField(db_column='Estado')),
                ('fk_categoria', models.ForeignKey(db_column='fk_categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='administracion_app.categorias')),
                ('fk_marca', models.ForeignKey(db_column='fk_marca', on_delete=django.db.models.deletion.DO_NOTHING, to='administracion_app.marcas')),
                ('fk_presentacion', models.ForeignKey(db_column='fk_presentacion', on_delete=django.db.models.deletion.DO_NOTHING, to='administracion_app.presentacion')),
                ('fk_unidad_medida', models.ForeignKey(db_column='fk_unidad_medida', on_delete=django.db.models.deletion.DO_NOTHING, to='administracion_app.unidadesmedidas')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id_mov_caja', models.AutoField(db_column='ID_mov_caja', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=50)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=150, null=True)),
                ('monto_total', models.DecimalField(db_column='Monto_total', decimal_places=4, max_digits=19)),
                ('fk_tipo_movimiento', models.ForeignKey(db_column='fk_tipo_movimiento', on_delete=django.db.models.deletion.DO_NOTHING, to='administracion_app.movimientos')),
            ],
        ),
        migrations.CreateModel(
            name='ListadoPedidos',
            fields=[
                ('id_listado', models.BigAutoField(db_column='ID_listado', primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(db_column='Fecha_creacion')),
                ('estado', models.BooleanField(db_column='Estado')),
                ('fk_empleado', models.ForeignKey(db_column='fk_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='administracion_app.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(db_column='ID_inventario', primary_key=True, serialize=False)),
                ('fecha_ultima_salida', models.DateField(blank=True, null=True)),
                ('fecha_ultima_entrada', models.DateField(blank=True, null=True)),
                ('total_stock', models.IntegerField(blank=True, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fk_producto2', models.ForeignKey(blank=True, db_column='fk_producto2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion_app.productos')),
            ],
        ),
        migrations.AddField(
            model_name='empleados',
            name='fk_id_puesto',
            field=models.ForeignKey(blank=True, db_column='fk_id_puesto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion_app.puestos'),
        ),
        migrations.CreateModel(
            name='DetalleVentas',
            fields=[
                ('id_detalle_venta', models.AutoField(db_column='ID_detalle_venta', primary_key=True, serialize=False)),
                ('cantidad_producto', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fk_id_producto1', models.ForeignKey(blank=True, db_column='fk_id_producto1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion_app.productos')),
                ('fk_venta', models.ForeignKey(blank=True, db_column='fk_venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion_app.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleListadoDePedidos',
            fields=[
                ('id_ls_detalle_producto', models.BigAutoField(db_column='ID_ls_detalle_producto', primary_key=True, serialize=False)),
                ('cantidad_a_comprar', models.IntegerField(db_column='Cantidad_a_comprar')),
                ('fk_listado_pedido', models.ForeignKey(db_column='fk_listado_pedido', on_delete=django.db.models.deletion.DO_NOTHING, to='administracion_app.listadopedidos')),
                ('fk_producto3', models.ForeignKey(db_column='fk_Producto3', on_delete=django.db.models.deletion.DO_NOTHING, to='administracion_app.productos')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle_compra', models.BigAutoField(db_column='ID_detalle_compra', primary_key=True, serialize=False)),
                ('descuentos', models.DecimalField(blank=True, db_column='Descuentos', decimal_places=2, max_digits=18, null=True)),
                ('cantidad_compra', models.IntegerField(db_column='Cantidad_compra')),
                ('precio_unitario_compra', models.DecimalField(decimal_places=2, max_digits=18)),
                ('precio_sugerido_venta', models.DecimalField(db_column='Precio_sugerido_venta', decimal_places=2, max_digits=18)),
                ('no_lote', models.IntegerField(db_column='No_lote')),
                ('fk_compra', models.ForeignKey(blank=True, db_column='fk_compra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion_app.compras')),
                ('fk_producto', models.ForeignKey(blank=True, db_column='fk_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion_app.productos')),
            ],
        ),
        migrations.AddField(
            model_name='compras',
            name='fk_empleado',
            field=models.ForeignKey(blank=True, db_column='fk_empleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion_app.empleados'),
        ),
        migrations.AddField(
            model_name='compras',
            name='fk_metodo_pago',
            field=models.ForeignKey(blank=True, db_column='fk_metodo_pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion_app.metodospago'),
        ),
        migrations.AddField(
            model_name='compras',
            name='fk_proveedor',
            field=models.ForeignKey(blank=True, db_column='fk_proveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion_app.proveedores'),
        ),
    ]
